#spring.application.name=pogreb
server:
  port: 9090
spring:
  database:
    url: jdbc:postgresql://localhost:5444/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgres.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect